# To use these prefixes you need additionally the pistonchat.<COLORCODE>
# / indicates disabled!
# This config is configured to be what 2b2t.org has.
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
# pistonchat.prefix.green and pistonchat.chatformat.default are given by default.
# storage is either file or mysql

whisper:
  from: "<light_purple><player_name> whispers: <message>"
  to: "<light_purple>You whisper to <player_name>: <message>"
hover-text: "<gold>Message <dark_aqua><player_name>"

storage: "file"
mysql:
  host: "localhost"
  port: 3306
  database: "pistonchat"
  username: "root"
  password: ""

strip-name-color: true
chat-formats:
  special: "<player_name> Â»"
  default: "<<player_name>>"

message-format: "<format> <message>"

console-name: "[console]"

allow-pm-self: true
allow-pm-ignored: true
only-hide-pms: true

ignore-list-size: 9

messages:
  # The prefix can also be set to just "&6"
  format: "[<dark_green>PistonChat</dark_green>] <gold><message>"
  help-header: "---[<dark_green>PistonChat</dark_green>]---"
  playeronly: "You need to be a player to do this."
  notonline: "This player is not online."
  nooneignored: "No players ignored."
  chaton: "Chat messages unhidden."
  chatoff: "Chat messages hidden."
  pmson: "Private messages unhidden."
  pmsoff: "Private messages hidden."
  pmself: "Please do not private message yourself."
  chatisoff: "You have toggled off chat"
  source-ignored: "This person ignores you!"
  target-ignored: "You ignore this person!"
  page-not-exists: "This page doesn't exist."
  not-a-number: "Not a number!"
  whispering-disabled: "This person has whispering disabled!"
  ignore: "<gold>Now ignoring <dark_aqua><player_name>"
  unignore: "<gold>No longer ignoring <dark_aqua><player_name>"
  ignorehard: "<gold>Permanently ignoring <player_name>. This is saved in <dark_red>/ignorelist</dark_red>."
  unignorehard: "<gold>No longer permanently ignoring <dark_aqua><player_name>"
  ignorelistcleared: "<gold>Ignore list cleared."

prefixes:
  green:
    prefix: ">"
    color: "GREEN"
